#Data Pipeline
code_path: /app/code
input_path: /app/source
output_path: /app/target
log_path: /app/logs

source_file1: characters.csv
source_file2: characters_stats.csv

# Database configuration
database:
  db_name: db_sil_marvel
  table_name: char_stats_day_dly
  ddl_script: modelling.sql
  analytics_script: analytics.sql

# Monitoring
monitoring_path: /app/monitoring
load_status_table: load_daily_status
teams_webhook_url: https://outlook.office.com/webhook/ENTER_WEBHOOK_URL_HERE

# unit testing
table_name: char_stats_day_dly
primary_key_columns:
  - characterID
  - name
threshold_percentage: 10
table_name: char_stats_day_dly
columns:
  - {name: name, type: string}
  - {name: characterID, type: int}
  - {name: Alignment, type: string}
  - {name: Intelligence, type: int}
  - {name: Strength, type: int}
  - {name: Speed, type: int}
  - {name: Durability, type: int}
  - {name: Power, type: int}
  - {name: Combat, type: int}
  - {name: Total, type: int}
  - {name: batch_id, type: string}
  - {name: load_date, type: string}


# Spark configuration
spark:
  app_name: UnitTest






